main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('plants/', views.plant_index, name='plant-index'),
  path('plants/<int:plant_id>/', views.plant_detail, name='plant-detail'),
  path('plants/create/', views.PlantCreate.as_view(), name='plant-create'),
  path('plants/create/', views.PlantCreate.as_view(), name='plant-create'),
  path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plant-update'),
  path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plant-delete'),
  path('plants/<int:plant_id>/add-feeding/', views.add_feeding, name='add-feeding'),
  path('accounts/signup/', views.signup, name='signup'),
  path('plants/<int:plant_id>/add-photo/', views.add_photo, name='add-photo'),
]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

WATERING = (
  ('M', 'Morning'),
  ('A', 'Afternoon'),
  ('N', 'Night')
)

class Plant(models.Model):
    species = models.CharField(max_length=100)
    description = models.TextField()
    height = models.IntegerField()
    watering_frequency = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
      return self.species

    def get_absolute_url(self):
      return reverse('plant-detail', kwargs={'plant_id': self.id})

class Feeding(models.Model):
  date = models.DateField('Watering time')
  watering = models.CharField(
    max_length=1,
    choices=WATERING,
    default=WATERING[0][0]
  )

  plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_watering_display()} on {self.date}"

class Photo(models.Model):
  url = models.CharField(max_length=250)
  plant = models.OneToOneField(Plant, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for plant_id: {self.plant_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'watering']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Plant, Photo
import uuid
import boto3
from .forms import FeedingForm
S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET = 'rich-plant-collector'



class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')
@login_required
def plant_index(request):
    plants = Plant.objects.filter(user=request.user)
    return render(request, 'plants/index.html', { 'plants': plants })

def plant_detail(request, plant_id):
  plant = Plant.objects.get(id=plant_id)
  feeding_form = FeedingForm()
  return render(request, 'plants/detail.html', {
    'plant': plant, 'feeding_form': feeding_form
  })

def add_feeding(request, plant_id):
  form = FeedingForm(request.POST)
  if form.is_valid():
    new_feeding = form.save(commit=False)
    new_feeding.plant_id = plant_id
    new_feeding.save()
  return redirect('plant-detail', plant_id=plant_id)

class PlantCreate(LoginRequiredMixin, CreateView):
  model = Plant
  fields = ['species', 'description', 'watering_frequency', 'height']

  def form_valid(self, form):
    form.instance.user = self.request.user 
    return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
  model = Plant
  fields = ['species', 'description', 'watering_frequency', 'height']

class PlantDelete(LoginRequiredMixin, DeleteView):
  model = Plant
  success_url = '/plants/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('plant-index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

def add_photo(request, plant_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = Photo(url=url, plant_id=plant_id)
      plant_photo = Photo.objects.filter(plant_id=plant_id)
      if plant_photo.first():
        plant_photo.first().delete()
      photo.save()
    except Exception as err:
      print('An error occurred uploading file to S3: %s' % err)
  return redirect('plant-detail', plant_id=plant_id)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/potted-plant (1).svg' %}"
  >
  <title>Plant Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>

    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'plant-index' %}">Garden</a></li>
          <li><a href="{% url 'plant-create' %}">Add a plant</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %} 
    </ul>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/homelogin.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="plant-container">
    <img class="plantlogo" src="{% static 'images/potted-plant.svg' %}" alt="" />
  </div>

</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/comfirm.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">

  <h1>Delete plant?</h1>
</div>

<h2>Are you sure you want to set {{plant.species}} free?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'plant-detail' plant.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Release {{plant.species}}!</button>
</form>

{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
  {% if plant %}
    <h1>Edit {{ plant.species }}</h1>
  {% else %}
    <h1>Add a plant</h1>
  {% endif %}
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/plants/plantdetail.css' %}"
/>

<script defer src="{% static 'js/plant-detail.js' %}"></script>

{% endblock %}

{% block content %}

  <div class="plant-img">
    {% if plant.photo.url %}
      <img 
        src="{{plant.photo.url}}" 
        alt="A photo of {{plant.species}}"
        class="usr-img"
      >
    {% else %}
      <img 
        src="{% static 'images/Plantlogo.svg' %}" 
        alt=""
        class=""
      >
    {% endif %}
  </div>
  <section class="plant-container">

  <div class="plant-details">
    <h1>{{ plant.species }}</h1>
    {% if plant.height > 0 %}
    {% else %}
      <p>{{ plant.species }} </p>
    {% endif %}
    <p>{{ plant.description }}</p>
    <p><strong>Needs to be watered: </strong>{{ plant.watering_frequency }}</p>
    <p><strong>Height: </strong> {{ plant.height }} inch</p>

    <div class="plant-actions">
      <a href="{% url 'plant-update' plant.id %}" class="btn warn">Edit</a>
      <a href="{% url 'plant-delete' plant.id %}" class="btn danger">Delete</a>
    </div>
    <h3>Change {{plant.species }}'s photo</h3>
    <p id="file-name"></p>
    <form 
      action="{% url 'add-photo' plant.id %}"
      enctype="multipart/form-data"
      method="POST"
    >
      {% csrf_token %}
      <label class="btn secondary">
        Choose photo
        <input type="file" name="photo-file" id="file-input">
      </label>
      <button type="submit" class="btn submit">Upload Photo</button>
    </form>
  </div>
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>waterings</h2>
    </div>
    <h3>Watering schedule </h3>
    <form
      action="{% url 'add-feeding' plant.id %}" 
      method="post" 
      class="subsection-content"
      autocomplete="off"
    >
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <button type="submit" class="btn submit">Add Watering</button>
    </form>
    <h3>Past Watering</h3>
    {% if plant.feeding_set.all.count %}
      <table>
        <thead>
          <tr><th>Date</th><th>Watering</th></tr>
        </thead>
        <tbody>
          {% for feeding in plant.feeding_set.all %}
            <tr>
              <td>{{feeding.date}}</td>
              <td>{{feeding.get_watering_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="subsection-content">
        <p>{{plant.species}} has never been watered 😔</p>
      </div>
    {% endif %}
  </section>
</div>
</section>


{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/plants/plant-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Garden</h1>
  <img src="{% static 'images/potted-plant (1).svg' %}" alt="" />

</section>

<section class="card-container">
  {% for plant in plants %}
    <div class="card">
      <a href="/plants/{{ plant.id }}">
        <div class="card-content">
          <div class="card-img-container">
            {% if plant.photo.url %}
            <img 
              src="{{plant.photo.url}}" 
              alt="A photo of {{plant.species}}"
              class="usr-img"
            >
            {% else %}
            <img 
              src="{% static 'images/potted-plant (1).svg' %}" 
              alt=""
            >
            {% endif %}
          </div>
          <h2 class="card-title">{{ plant.species }}</h2>
          {% if plant.height > 0 %}
            <p>A {{ plant.height }} inch {{ plant.species }}</p>
          {% else %}
            <p>{{ plant.species }} </p>
          {% endif %}
          <p class='plantdescription'><small>{{ plant.description }}</small></p>
        </div>
      {% comment %} And this line {% endcomment %}
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container"  autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}